# Generated by Django 3.2.7 on 2021-10-06 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Name')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Email')),
                ('password', models.CharField(max_length=500, verbose_name='Password')),
                ('token', models.CharField(max_length=500, verbose_name='Token')),
                ('token_expire', models.DateField(verbose_name='Token Expire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Datetime')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated Datetime')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
